# Generated by Django 5.2.15 on 2026-09-07 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingStockTransaction',
            fields=[
                ('pending_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stock_requests', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_transactions', to='catalog.item')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_stock_requests', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.room')),
            ],
            options={
                'db_table': 'pending_stock_transactions',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomItemHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('moved_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('from_room', models.ForeignKey(db_column='from_room_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_from', to='catalog.room')),
                ('item', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, related_name='room_history', to='catalog.item')),
                ('to_room', models.ForeignKey(db_column='to_room_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_to', to='catalog.room')),
                ('user', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_moves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'room_item_history',
                'ordering': ['-moved_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJUST', 'Adjustment')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='catalog.item')),
                ('user', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stock_transactions',
                'ordering': ['-timestamp'],
            },
        ),
    ]
