# Generated by Django 4.2.7 on 2026-09-08 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remap_legacy_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, default='', max_length=254)),
                ('event', models.CharField(choices=[('login', 'Signed in'), ('failed', 'Failed sign-in'), ('logout', 'Signed out')], default='login', max_length=20)),
                ('successful', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('client', models.CharField(blank=True, default='', max_length=120)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'login_events',
                'ordering': ['-timestamp', '-event_id'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='login_event_user_id_b4867a_idx'), models.Index(fields=['successful', '-timestamp'], name='login_event_success_9fc40c_idx')],
            },
        ),
    ]
