# Generated by Django 4.2.7 on 2026-09-08 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_history(apps, schema_editor):
    """Existing 'issued' requisitions were fully handed out; seed that plus a
    'created' event so old rows have at least the start of a timeline."""
    Requisition = apps.get_model("requisitions", "Requisition")
    RequisitionItem = apps.get_model("requisitions", "RequisitionItem")
    RequisitionEvent = apps.get_model("requisitions", "RequisitionEvent")

    RequisitionItem.objects.filter(requisition__status="issued").update(
        issued_quantity=models.F("quantity")
    )

    for req in Requisition.objects.all().iterator():
        event = RequisitionEvent.objects.create(
            requisition=req,
            event_type="created",
            actor_id=req.user_id,
            to_status="pending",
            note="",
            metadata={},
        )
        RequisitionEvent.objects.filter(pk=event.pk).update(created_at=req.created_at)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requisitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionitem',
            name='issued_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('partially_issued', 'Partially Issued'), ('issued', 'Issued'), ('returned', 'Returned')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='RequisitionEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('partially_issued', 'Partially issued'), ('issued', 'Issued'), ('returned', 'Returned'), ('comment', 'Comment')], max_length=20)),
                ('from_status', models.CharField(blank=True, default='', max_length=20)),
                ('to_status', models.CharField(blank=True, default='', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, db_column='actor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisition_events', to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(db_column='req_id', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='requisitions.requisition')),
            ],
            options={
                'db_table': 'requisition_events',
                'ordering': ['created_at', 'event_id'],
            },
        ),
        migrations.RunPython(backfill_history, migrations.RunPython.noop),
    ]
