# Generated by Django 4.2.7 on 2026-09-08 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp', '-log_id']},
        ),
    ]
