# Generated by Django 4.2.7 on 2026-09-09 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_item_opening_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-item_id']},
        ),
    ]
