# Generated by Django 4.2.7 on 2026-09-08 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_handover(apps, schema_editor):
    """Rows created under the old single-step flow were approved and handed over
    by the same person in one action, so credit the approver with the handover."""
    KeyBorrow = apps.get_model("keys", "KeyBorrow")
    KeyBorrow.objects.filter(
        borrowed_at__isnull=False, handed_over_by__isnull=True, approver__isnull=False
    ).update(
        handed_over_by=models.F("approver"),
        handover_notes="Recorded before handover confirmation was a separate step.",
    )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('keys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyborrow',
            name='handed_over_by',
            field=models.ForeignKey(blank=True, db_column='handed_over_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_handovers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='keyborrow',
            name='handover_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='keyauditlog',
            name='action',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('returned', 'Returned'), ('lost', 'Lost'), ('found', 'Found'), ('maintenance', 'Sent to Maintenance'), ('restored', 'Restored'), ('created', 'Created'), ('borrowed', 'Borrowed'), ('approved', 'Borrow Approved'), ('picked_up', 'Handover Confirmed'), ('rejected', 'Borrow Rejected'), ('returned_borrow', 'Returned from Borrow')], max_length=20),
        ),
        migrations.RunPython(backfill_handover, migrations.RunPython.noop),
    ]
