# Generated by Django 4.2.7 on 2026-09-09 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0002_keyborrow_handed_over_by_keyborrow_handover_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomkey',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('in_use', 'In Use'), ('lost', 'Lost'), ('maintenance', 'Maintenance')], default='available', max_length=20),
        ),
    ]
